default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: yogadose_development
  password:

test:
  <<: *default
  database: yogadose_test

production:
  <<: *default
  database: yogadose_production
  username: yogadose
  password: <%= ENV['YOGADOSE_DATABASE_PASSWORD'] %>
