default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: db
  port: 5432

development:
  <<: *default
  database: yogadose_development
  # password:
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: yogadose_test

production:
  <<: *default
  database: yogadose_production
  username: yogadose
  password: <%= ENV['YOGADOSE_DATABASE_PASSWORD'] %>
